### PR TITLE
Another small FPGA/SoC cleanups

### PR DESCRIPTION
**Pull request by enjoy-digital**
Here is another pass of small cleanups, mostly to improve presentation/readability and avoid too much duplications.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Possible it has becomes difficult to review and maybe not going in the direction you want. Please tell me if so, i could do smaller PR and/or remove/avoid some changes. The idea is still just to simplify/cleanup the FPGA/SoC codebase to ease contributions/refactoring later.

**Comment by bunnie** [comment]
i'm checking out your latest set of changes and doing some regression and digging around to understand all the changes -- so far they mostly make sense to me and look good, will comment more later.

**Comment by enjoy-digital** [comment]
OK, i think i'm done with these small changes. I've identified others things but will create specific issues for that to discuss since it could be some design choices you specifically made.

**Comment by bunnie** [comment]
it built well and seems to work. I will do a little more code review on the sim directory later today -- right now hacking on the JTAG stuff at CCC, and the soldering iron is hot so need to take care of that :)

**Comment by bunnie** [comment]
looking good...

**Pull request merged**
