### PR TITLE
betrusted-soc/CRG: use LiteX's S7MMCM and remove slow_clock mode

### PR DESCRIPTION
**Pull request by enjoy-digital**
As discussed in https://github.com/betrusted-io/betrusted-soc/issues/11, this should simplify the design and ease changing/adding clock frequencies in the future.

### CODE REVIEW

**Comment by enjoy-digital** [comment]
Have you been able to test it on hardware?

**Comment by bunnie** [comment]
stepped out for dinner as it's compiling. I'll load it up once I'm back home in about an hour. 

thanks, 

-b. 
--

**Comment by enjoy-digital** [comment]
ok, BTW if you are not already aware of it, it's possible to test a pull request locally without merging it yet: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

**Comment by bunnie** [comment]
I didn't know about this! that's very helpful, thanks.

The design seems to work OK, but some other bugs have crept in that I think are from other changes I made. I had also pulled the latest litex, which maybe wasn't the smartest idea for comparing revs. I'll keep digging into the current problem but I doubt it would be caused by the clock network refactor unless it somehow clobbered the UART baud generator.

**Comment by bunnie** [comment]
can confirm everything is looking good, figured out the last few bugs.

**Comment by enjoy-digital** [comment]
OK good, then i'll do some tests with the timings constraints as discussed in https://github.com/betrusted-io/betrusted-soc/issues/10 and will send a PR.

**Pull request merged**
